### ISSUE TITLE
App not showing result

### ISSUE THREAD

**Issue by ghost** [marsf/Protractor2D#2]
App is not showing any result.
Device: Alcatel Pixi 3 FF
Firefox 2.0
![2015-11-10-16-20-46](https://cloud.githubusercontent.com/assets/15785828/11066712/9848c256-87c9-11e5-95a8-2763301547d8.png)

**Comment by marsf** [comment]
Can you please confirm the issue is fixed?

To comfirm instantly on your device, clone this git repository, and install this app using WebIDE on Firefox.
Or, please wait for an update on Marketplace.
Thank you for your report.

**Comment by marsf** [comment]
Here is another issue.
Camera preview is not rotated correctly on your device.

If you could get confirmed with WebIDE, please check the log at console panel of WebIDE, and tell me the line of `adjustVideoArea() - sensorAngle: ...`.

**Comment by ghost** [comment]
Controls and result are visible now, the line at WebIDE shows:
adjustVideoArea() -  sensorAngle: 90 Ratio: 1.5 videoElement: width: 480px;
height: 320px; transform-origin: 33.3% 50% 0px; transform: rotate(90deg);

2015-11-11 6:25 GMT+01:00 Masahiko Imanaka notifications@github.com:

**Comment by marsf** [comment]
Thanks!
Rotation probrem is separated to issue #3.
